AWSTemplateFormatVersion: "2010-09-09"
<<<<<<< feature/aws-study-11-network-ec2
Description: Study environment network compute and database
# ---------------------------------------
# AWS Study 11
# network → compute → database
# 段階的にスタック作成して動作確認するテンプレート
# ---------------------------------------

# テンプレートを再利用可能にするため、
# DBName、InStanceTypeとKeyNameもParameter化
Parameters:
  DBMasterPassword:
    Type: String
    NoEcho: true

  InstanceType:
    Type: String
    Default: t2.micro

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  
  DBName:
    Type: String
    Default: awsstudy


Resources:
  # VPC
  StudyVPC:
=======
Description: AWS-Study Template

Resources:
  MyVPC:
>>>>>>> main
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
<<<<<<< feature/aws-study-11-network-ec2
      EnableDnsHostnames: true
=======
      EnableDnsHostnames: true # 名前解決用としてtrue設定
>>>>>>> main
      Tags:
        - Key: Name
          Value: aws-study-vpc

<<<<<<< feature/aws-study-11-network-ec2

  # Subnet 
  # PublicSubnetはALBアクセス用 
  StudyPublicSubnetAz1a:
    Type: AWS::EC2::Subnet 
    Properties: 
      VpcId: !Ref StudyVPC 
      CidrBlock: 10.1.1.0/24
      # 学習課題としてEC2へSSH接続して動作確認を行うためにtrueを設定
      MapPublicIpOnLaunch: true
      # AZを固定値（ap-northeast-1a）ではなく
      # !GetAZsで動的取得することで他のリージョンでも再利用可能にしている
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags: 
        - Key: Name 
          Value: aws-study-public-subnet1a 
          
          
  StudyPublicSubnetAz1c:
    Type: AWS::EC2::Subnet 
    Properties:
      VpcId: !Ref StudyVPC 
      CidrBlock: 10.1.2.0/24
      # 学習課題としてEC2へSSH接続して動作確認を行うためにtrueを設定
      MapPublicIpOnLaunch: true
      # AZを固定値（ap-northeast-1c）ではなく
      # !GetAZsで動的取得することで他のリージョンでも再利用可能にしている
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags:
        - Key: Name
          Value: aws-study-public-subnet1c


  # PrivateSubnetはRDSアクセス用 
  StudyPrivateSubnetAz1a:
    Type: AWS::EC2::Subnet
    Properties: 
      VpcId: !Ref StudyVPC 
      CidrBlock: 10.1.11.0/24
      # AZを固定値（ap-northeast-1a）ではなく
      # !GetAZsで動的取得することで他のリージョンでも再利用可能にしている
      AvailabilityZone: !Select [0, !GetAZs ""]
      Tags: 
        - Key: Name 
          Value: aws-study-private-subnet1a
  
  StudyPrivateSubnetAz1c: 
    Type: AWS::EC2::Subnet 
    Properties: 
      VpcId: !Ref StudyVPC 
      CidrBlock: 10.1.12.0/24
      # AZを固定値（ap-northeast-1c）ではなく
      # !GetAZsで動的取得することで他のリージョンでも再利用可能にしている
      AvailabilityZone: !Select [1, !GetAZs ""]
      Tags: 
        - Key: Name 
          Value: aws-study-private-subnet1c


  # インターネット通信を可能にするInternet Gatewayの作成
  # （EC2にSSH接続して動作確認を行う学習課題のため）
  StudyInternetGateway:  
=======
  # Subnet（2つともパブリックIPを自動付与可能にする）
  SubnetAZ1a: 
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.1.1.0/24
      VpcId: !Ref MyVPC
      AvailabilityZone: ap-northeast-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: aws-study-subnet1a

  SubnetAZ1c:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.1.2.0/24
      VpcId: !Ref MyVPC
      AvailabilityZone: ap-northeast-1c
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: aws-study-subnet1c


  # InternetGateway
  MyInternetGateway:
>>>>>>> main
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: aws-study-igw


<<<<<<< feature/aws-study-11-network-ec2
  # EC2にSSH接続して動作確認を行うため、Internet GatewayをVPCにアタッチし、
  # 0.0.0.0/0をIGWに向けたルートの定義
  StudyVPCGatewayAttachment: 
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref StudyVPC
      InternetGatewayId: !Ref StudyInternetGateway


  # パブリックサブネット用のルートテーブル。
  # 0.0.0.0/0をInternet Gatewayに向けることでインターネット通信を可能にしている。
  StudyPublicRouteTable: 
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref StudyVPC
      Tags:
        - Key: Name
          Value: aws-study-public-rt


  # インターネット向け通信（0.0.0.0/0）をInternet Gateway経由で許可するルート定義
  StudyPublicRoute: 
    Type: AWS::EC2::Route
    DependsOn: StudyVPCGatewayAttachment
    Properties:
      RouteTableId: !Ref StudyPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0 
      GatewayId: !Ref StudyInternetGateway   


  # サブネットとルートテーブルの関連付け
  StudySubnetRouteTableAssociationAz1a: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref StudyPublicRouteTable
      SubnetId: !Ref StudyPublicSubnetAz1a

  StudySubnetRouteTableAssociationAz1c: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref StudyPublicRouteTable
      SubnetId: !Ref StudyPublicSubnetAz1c


  # EC2用セキュリティグループ
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: AWS Study EC2
      VpcId: !Ref StudyVPC
=======
  # VPCGatewayAttachment
  MyVPCGatewayAttachment: 
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway


  # RouteTable
  MyRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref MyVPC
      Tags:
        - Key: Name
          Value: aws-study-route


  # インターネット向け通信（0.0.0.0/0）をInternet Gateway経由で許可するルート定義。
  MyRouteInternet:
    Type: AWS::EC2::Route
    DependsOn: MyVPCGatewayAttachment 
    Properties:
      RouteTableId: !Ref MyRouteTable
      DestinationCidrBlock: 0.0.0.0/0 
      GatewayId: !Ref MyInternetGateway   


  # 各サブネットとルートテーブルを関連付け（パブリックサブネット化）
  MyRouteLocal: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MyRouteTable
      SubnetId: !Ref SubnetAZ1a

  # ALBやRDSを配置するSubnetAZ1cもインターネットアクセスできるように関連付け
  MyRouteLocal2: 
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref MyRouteTable
      SubnetId: !Ref SubnetAZ1c


  MySecurityGroupEC2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: AWS Study EC2
      VpcId: !Ref MyVPC
>>>>>>> main
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
<<<<<<< feature/aws-study-11-network-ec2
          CidrIp: 210.128.165.154/32
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ALBSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: aws-study-ec2-sg
  

  # EC2インスタンス
  StudyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      # AMIを固定値化（SSM Parameterでの取得は望んでいない最新化が発生する可能性があるため）
      ImageId: ami-09cd9fdbf26acc6b4
      # 固定値からParameter化に変更
      InstanceType: !Ref InstanceType
      SubnetId: !Ref StudyPublicSubnetAz1a
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      # 固定値からParameter化に変更
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: aws-study-ec2


  # ALB用セキュリティグループ
  ALBSecurityGroup: 
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: AWS Study ALB
      VpcId: !Ref StudyVPC
      SecurityGroupIngress:
=======
          CidrIp: 0.0.0.0/0
>>>>>>> main
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
<<<<<<< feature/aws-study-11-network-ec2
      # 明示的に追加（アウトバウンドルールの設定も必要なため）
      SecurityGroupEgress: 
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: aws-study-alb-sg


  # ロードバランサー
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: aws-study-alb
      Scheme: internet-facing
      Type: application
      Subnets: 
        - !Ref StudyPublicSubnetAz1a
        - !Ref StudyPublicSubnetAz1c
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Tags:
        - Key: Name
          Value: aws-study-alb


  # ターゲットグループ
  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    # 依存関係を明示するため追加
    DependsOn: StudyEC2Instance
    Properties:
      Name: aws-study-tg
      VpcId: !Ref StudyVPC
      Protocol: HTTP
      Port: 8080
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckPort: "traffic-port"
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 5
      HealthCheckIntervalSeconds: 30
      Matcher: 
        HttpCode: 200-301
      Targets:
        - Id: !Ref StudyEC2Instance
          Port: 8080
      Tags:
        - Key: Name
          Value: aws-study-tg


  # ALB Listener（HTTPリクエストをALBTargetGroupへ転送）
  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Protocol: HTTP
      Port: 80
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
  

  # RDS用セキュリティグループ（EC2からのみ接続許可）
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref StudyVPC
      GroupDescription: AWS Study RDS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref EC2SecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      # タグ名の追加
      Tags:
        - Key: Name
          Value: aws-study-rds-sg
  

  # DBサブネットグループ
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties: 
      DBSubnetGroupDescription: subnet group for rds
      SubnetIds:
        - !Ref StudyPrivateSubnetAz1a
        - !Ref StudyPrivateSubnetAz1c
      # タグ名の追加
      Tags:
        - Key: Name
          Value: aws-study-db-subnet-group


  # RDSインスタンス（EC2からのみ接続可能なMySQLデータベース）
  RDSInstance:
    Type: AWS::RDS::DBInstance
    # 削除保護の二重対策として追加（Stack削除時とDB再作成時でのデータ消去を防ぐため）
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      Engine: mysql
      EngineVersion: 8.0.43
      MasterUsername: admin
      MasterUserPassword: !Ref DBMasterPassword
      DBInstanceClass: db.t4g.micro
      StorageType: gp3
      AllocatedStorage: 20
      Port: 3306
      DBSubnetGroupName: !Ref DBSubnetGroup
      PubliclyAccessible: false
      LicenseModel: general-public-license
      VPCSecurityGroups:
        - !Ref RDSSecurityGroup
      # 固定値からParameter化に変更
      DBName: !Ref DBName
      # RDSのバックアップを0日から7日に変更
      BackupRetentionPeriod: 7
      EnableCloudwatchLogsExports:
        - error
        - slowquery
      AutoMinorVersionUpgrade: true
      DeletionProtection: false
      Tags:
        - Key: Name
          Value: aws-study-rds


# スタック作成後に各リソースの識別情報を確認しやすくするため、
# CloudFormationのOutputsに主要リソース情報を出力する。
# ALBはDNS名でアクセスする必要があるため、ブラウザからの接続確認用として出力。
# EC2InstanceIdはインスタンスの特定や運用時の確認を容易にするため出力。
# RDSEndpointはEC2などのアプリケーションからデータベース接続する時の接続先確認のため出力。
Outputs:
  ALBDNSName:
    Description: ALB DNS Name
    Value: !GetAtt ApplicationLoadBalancer.DNSName

  EC2InstanceId:
    Description: EC2 Instance ID
    Value: !Ref StudyEC2Instance

  RDSEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address
=======
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: aws-study-securityGroup-ec2
  

  MyInstance:
  # EC2（Amazon Linux 2023, t2.micro）
    Type: AWS::EC2::Instance
    Properties:
  # Amazon Linux 2023の最新AMIをSSMパラメータストアから取得
      ImageId: !Sub "resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64"
      InstanceType: t2.micro
      SubnetId: !Ref SubnetAZ1a
      DisableApiTermination: false
      InstanceInitiatedShutdownBehavior: stop
      SecurityGroupIds:
        - !Ref MySecurityGroupEC2
      KeyName: aws-dev-20250514
      Monitoring: false
      Tags:
        - Key: Name
          Value: aws-study-ec2
>>>>>>> main
